# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: StreamParticles staging CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0

      - name: Install
        run: npm ci

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1

      - name: Test
        run: npm run test

      - name: Linter
        run: npm run lint

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy staging app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/staging/streamParticles_front
            git pull origin development
            yarn install
            yarn build:staging

            cd ~/staging/streamParticles_back
            git pull origin master
            npm install
            tsc
            pm2 restart staging
